services:
    postgres:
        image: postgres:16
        container_name: postgres
        env_file:
            - app.env
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        cpus: '4'
        mem_limit: 6G

    redis:
        image: redis:7
        container_name: redis
        ports:
            - "6379:6379"
        restart: unless-stopped
        cpus: '1'
        mem_limit: 2G

    app:
        build: .
        container_name: NextTick-app
        network_mode: host

        ulimits:
            nofile:
                soft: 100000
                hard: 100000

        depends_on:
            - postgres
            - redis

        env_file:
            - app.env

        command: ["./wait-for-it.sh", "localhost:5432", "--", "java", "-Xms4G", "-Xmx4G", "-jar", "app.jar"]
        restart: unless-stopped
        cpus: '4'
        mem_limit: 6G

volumes:
    postgres_data:
