plugins {
	alias(libs.plugins.spring.boot)
	alias(libs.plugins.dependency.management)
}

jar.enabled=false
base {
	archivesName = "nexttick.backend"
}

dependencies {
	implementation project(":domain")
	implementation project(":application")
	implementation project(":infrastructure")
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.flywaydb:flyway-core'
	implementation 'org.flywaydb:flyway-database-postgresql'
	implementation libs.springdoc.openapi.ui
	compileOnly libs.lombok
	annotationProcessor libs.lombok

	runtimeOnly 'org.postgresql:postgresql'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webflux'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
